import { useState, useEffect, useRef } from 'react'
import { supabase } from '../../lib/supabase'
import { useAuth } from '../../hooks/useAuth'

const CATEGORY_COLORS = {
  Produce: '#8FA58C', Proteins: '#D4A0A0', Dairy: '#C4AFA8',
  Grains: '#C9B99B', Pantry: '#9B97C4', Other: '#7A6A65',
}

export default function BuildTab({ phase, phaseLabel, listId, onItemsAdded, autoGenerate, onAutoGenerateDone }) {
  const { user } = useAuth()

  // AI Phase Build state
  const [aiState, setAiState] = useState('idle') // idle | loading | preview | saving | saved
  const [aiItems, setAiItems] = useState([])
  const [removedIds, setRemovedIds] = useState(new Set())
  const [aiError, setAiError] = useState(null)

  // Manual add state
  const [manualInput, setManualInput] = useState('')
  const [manualLoading, setManualLoading] = useState(false)
  const [staged, setStaged] = useState([])
  const [stagingErr, setStagingErr] = useState(null)
  const inputRef = useRef(null)

  // Auto-generate on first visit if requested
  useEffect(() => {
    if (autoGenerate && aiState === 'idle') {
      handleGenerate()
    }
  }, [autoGenerate])

  async function handleGenerate() {
    setAiState('loading')
    setAiError(null)
    setAiItems([])
    setRemovedIds(new Set())
    try {
      const res = await fetch('/.netlify/functions/ai-grocery', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ type: 'phase_list', phase }),
      })
      const data = await res.json()
      if (data.error) throw new Error(data.error)
      if (!Array.isArray(data) || data.length === 0) throw new Error('Empty response')
      setAiItems(data.map((item, i) => ({ ...item, _id: i })))
      setAiState('preview')
    } catch (err) {
      console.error('ai-grocery error:', err)
      setAiError('Something went wrong — tap Generate to try again.')
      setAiState('idle')
    } finally {
      if (onAutoGenerateDone) onAutoGenerateDone()
    }
  }

  async function handleSaveAiItems() {
    if (!user || aiState === 'saving') return
    const toSave = aiItems.filter(i => !removedIds.has(i._id))
    if (toSave.length === 0) return

    setAiState('saving')
    setAiError(null)

    try {
      let targetListId = listId
      if (!targetListId) {
        const { data: newList, error: listErr } = await supabase
          .from('grocery_lists')
          .insert({ user_id: user.id, title: `${phaseLabel} Phase List`, phase_name: phase, is_template: false })
          .select()
          .single()
        if (listErr || !newList?.id) {
          setAiError('Could not create your list — please try again.')
          setAiState('preview')
          return
        }
        targetListId = newList.id
      }

      const rows = toSave.map(item => ({
        list_id: targetListId,
        user_id: user.id,
        name: item.name,
        category: item.category ?? 'Other',
        quantity: item.quantity ?? 1,
        unit: item.unit ?? '',
        is_checked: false,
      }))

      const { error: insertErr } = await supabase.from('grocery_items').insert(rows)
      if (insertErr) {
        setAiError('Could not save items — please try again.')
        setAiState('preview')
        return
      }

      setAiState('saved')
      onItemsAdded(targetListId)
    } catch {
      setAiError('Something went wrong — please try again.')
      setAiState('preview')
    }
  }

  async function handleManualAdd() {
    const text = manualInput.trim()
    if (!text) return
    setManualLoading(true)
    setStagingErr(null)
    try {
      const res = await fetch('/.netlify/functions/ai-grocery', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ type: 'add_item', text }),
      })
      const parsed = await res.json()
      if (!parsed.name) throw new Error('Could not parse item')
      setStaged(prev => [...prev, { ...parsed, _sid: Date.now() }])
      setManualInput('')
      inputRef.current?.focus()
    } catch {
      setStagingErr('Could not parse that item — try rephrasing.')
    } finally {
      setManualLoading(false)
    }
  }

  async function handleCommitManual() {
    if (!user || staged.length === 0) return
    let targetListId = listId
    if (!targetListId) {
      const { data: newList } = await supabase
        .from('grocery_lists')
        .insert({ user_id: user.id, title: `My Grocery List`, phase_name: phase, is_template: false })
        .select()
        .single()
      targetListId = newList?.id
    }
    if (!targetListId) return

    const rows = staged.map(item => ({
      list_id: targetListId,
      user_id: user.id,
      name: item.name,
      category: item.category ?? 'Other',
      quantity: item.quantity ?? 1,
      unit: item.unit ?? '',
      is_checked: false,
    }))

    await supabase.from('grocery_items').insert(rows)
    setStaged([])
    onItemsAdded(targetListId)
  }

  return (
    <div>
      <style>{`
        @keyframes itemSlideIn {
          from { opacity: 0; transform: translateY(8px); }
          to { opacity: 1; transform: translateY(0); }
        }
        @keyframes pulseSage {
          0%,100% { opacity: 0.6; }
          50% { opacity: 1; }
        }
      `}</style>

      {/* ── AI Phase Build ─────────────────────────────────────────── */}
      <div style={{
        borderRadius: 16, overflow: 'hidden', marginBottom: 20,
        background: 'rgba(143,165,140,0.09)',
        border: '1px solid rgba(143,165,140,0.3)',
        padding: 20,
      }}>
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 12 }}>
          <div>
            <span style={{
              fontFamily: 'Helvetica Neue, sans-serif', fontSize: 9, letterSpacing: '0.18em',
              textTransform: 'uppercase', color: '#8FA58C',
              background: 'rgba(143,165,140,0.15)', padding: '3px 10px', borderRadius: 12,
            }}>
              {phaseLabel}
            </span>
            <h3 style={{ fontFamily: 'Cormorant Garamond, serif', fontSize: 18, fontStyle: 'italic',
              color: '#3B3330', marginTop: 8, marginBottom: 4 }}>
              Let Athena build your list.
            </h3>
            <p style={{ fontFamily: 'Helvetica Neue, sans-serif', fontSize: 12, color: '#7A6A65' }}>
              20 hormone-supportive items, curated for your {phaseLabel?.toLowerCase()} phase.
            </p>
          </div>
        </div>

        {aiState === 'idle' && (
          <button
            onClick={handleGenerate}
            style={{
              width: '100%', padding: '12px 0', borderRadius: 22, background: '#8FA58C',
              border: 'none', color: '#F2EDE8', fontFamily: 'Cinzel, serif', fontSize: 10,
              letterSpacing: '0.2em', textTransform: 'uppercase', cursor: 'pointer',
            }}
          >
            Generate My {phaseLabel} List
          </button>
        )}

        {aiState === 'loading' && (
          <div style={{ textAlign: 'center', padding: '20px 0' }}>
            <div style={{ display: 'flex', justifyContent: 'center', gap: 6, marginBottom: 12 }}>
              {[0, 1, 2].map(i => (
                <div key={i} style={{
                  width: 8, height: 8, borderRadius: '50%', background: '#8FA58C',
                  animation: `pulseSage 1.2s ease-in-out ${i * 0.2}s infinite`,
                }} />
              ))}
            </div>
            <p style={{ fontFamily: 'Cormorant Garamond, serif', fontSize: 15, fontStyle: 'italic',
              color: '#7A6A65' }}>
              Building your {phaseLabel?.toLowerCase()} list…
            </p>
          </div>
        )}

        {aiError && (
          <p style={{ fontFamily: 'Helvetica Neue, sans-serif', fontSize: 12, color: '#D4A0A0',
            marginTop: 8, textAlign: 'center' }}>
            {aiError}
          </p>
        )}

        {aiState === 'saved' && (
          <div style={{ textAlign: 'center', padding: '8px 0' }}>
            <p style={{ fontFamily: 'Cormorant Garamond, serif', fontSize: 16, fontStyle: 'italic', color: '#8FA58C' }}>
              Added to your list ✓
            </p>
            <button
              onClick={() => { setAiState('idle'); setAiItems([]); setRemovedIds(new Set()) }}
              style={{ background: 'none', border: 'none', cursor: 'pointer', marginTop: 6,
                fontFamily: 'Helvetica Neue, sans-serif', fontSize: 12, color: '#7A6A65',
                textDecoration: 'underline' }}>
              Regenerate
            </button>
          </div>
        )}
      </div>

      {/* ── AI Preview list ────────────────────────────────────────── */}
      {aiState === 'preview' && aiItems.length > 0 && (
        <div style={{ marginBottom: 20 }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 12 }}>
            <p style={{ fontFamily: 'Helvetica Neue, sans-serif', fontSize: 10, letterSpacing: '0.15em',
              textTransform: 'uppercase', color: '#7A6A65' }}>
              {aiItems.length - removedIds.size} items ready
            </p>
            <button
              onClick={() => { setAiState('idle'); setAiItems([]); setRemovedIds(new Set()) }}
              style={{ background: 'none', border: 'none', cursor: 'pointer',
                fontFamily: 'Helvetica Neue, sans-serif', fontSize: 11, color: '#7A6A65',
                textDecoration: 'underline' }}>
              Start over
            </button>
          </div>

          {aiItems.map((item, idx) => (
            !removedIds.has(item._id) && (
              <div
                key={item._id}
                style={{
                  background: 'rgba(255,255,255,0.52)', borderRadius: 10,
                  padding: '10px 12px', marginBottom: 4,
                  display: 'flex', alignItems: 'flex-start', gap: 10,
                  animation: `itemSlideIn 0.25s ease ${idx * 0.035}s both`,
                }}
              >
                <div style={{ flex: 1, minWidth: 0 }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 3 }}>
                    <p style={{ fontFamily: 'Cormorant Garamond, serif', fontSize: 15, color: '#3B3330' }}>
                      {item.quantity}{item.unit ? ` ${item.unit}` : ''} {item.name}
                    </p>
                    <span style={{
                      fontFamily: 'Helvetica Neue, sans-serif', fontSize: 8, letterSpacing: '0.1em',
                      textTransform: 'uppercase', padding: '2px 7px', borderRadius: 8,
                      background: `${CATEGORY_COLORS[item.category] ?? '#7A6A65'}20`,
                      color: CATEGORY_COLORS[item.category] ?? '#7A6A65',
                      flexShrink: 0,
                    }}>
                      {item.category}
                    </span>
                  </div>
                  {item.reason && (
                    <p style={{ fontFamily: 'Cormorant Garamond, serif', fontSize: 12, fontStyle: 'italic',
                      color: '#7A6A65', lineHeight: 1.4 }}>
                      {item.reason}
                    </p>
                  )}
                </div>
                <button
                  onClick={() => setRemovedIds(prev => new Set([...prev, item._id]))}
                  style={{ background: 'none', border: 'none', cursor: 'pointer',
                    color: 'rgba(122,106,101,0.4)', fontSize: 16, lineHeight: 1, flexShrink: 0,
                    padding: '2px 4px' }}
                >
                  ×
                </button>
              </div>
            )
          ))}

          <button
            onClick={handleSaveAiItems}
            disabled={aiState === 'saving'}
            style={{
              width: '100%', padding: '12px 0', borderRadius: 22,
              background: aiState === 'saving' ? 'rgba(143,165,140,0.5)' : '#8FA58C',
              border: 'none', color: '#F2EDE8', fontFamily: 'Cinzel, serif', fontSize: 10,
              letterSpacing: '0.2em', textTransform: 'uppercase',
              cursor: aiState === 'saving' ? 'default' : 'pointer',
              marginTop: 12,
            }}
          >
            {aiState === 'saving' ? 'Saving…' : 'Save to My List'}
          </button>
        </div>
      )}

      {/* ── Divider ────────────────────────────────────────────────── */}
      <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 20 }}>
        <div style={{ flex: 1, height: 1, background: 'rgba(196,175,168,0.35)' }} />
        <span style={{ fontFamily: 'Helvetica Neue, sans-serif', fontSize: 10, color: '#7A6A65',
          letterSpacing: '0.1em' }}>or add yourself</span>
        <div style={{ flex: 1, height: 1, background: 'rgba(196,175,168,0.35)' }} />
      </div>

      {/* ── Manual Add ─────────────────────────────────────────────── */}
      <div>
        <div style={{ display: 'flex', gap: 8, marginBottom: 12 }}>
          <input
            ref={inputRef}
            value={manualInput}
            onChange={e => setManualInput(e.target.value)}
            onKeyDown={e => e.key === 'Enter' && handleManualAdd()}
            placeholder="'2 cans chickpeas' or 'almond milk'"
            style={{
              flex: 1, padding: '11px 14px', borderRadius: 22,
              border: '1.5px solid rgba(232,196,188,0.6)',
              background: 'rgba(255,255,255,0.55)', backdropFilter: 'blur(8px)',
              fontFamily: 'Cormorant Garamond, serif', fontSize: 15, color: '#3B3330',
              outline: 'none',
            }}
          />
          <button
            onClick={handleManualAdd}
            disabled={!manualInput.trim() || manualLoading}
            style={{
              padding: '11px 18px', borderRadius: 22,
              background: manualInput.trim() ? '#3B3330' : 'rgba(196,175,168,0.2)',
              border: 'none', color: manualInput.trim() ? '#F2EDE8' : '#7A6A65',
              fontFamily: 'Cinzel, serif', fontSize: 9, letterSpacing: '0.15em',
              textTransform: 'uppercase', cursor: manualInput.trim() ? 'pointer' : 'default',
              flexShrink: 0,
            }}
          >
            {manualLoading ? '…' : 'Add'}
          </button>
        </div>

        {stagingErr && (
          <p style={{ fontFamily: 'Helvetica Neue, sans-serif', fontSize: 12, color: '#D4A0A0', marginBottom: 8 }}>
            {stagingErr}
          </p>
        )}

        {staged.length > 0 && (
          <div>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6, marginBottom: 12 }}>
              {staged.map(item => (
                <div key={item._sid} style={{
                  display: 'flex', alignItems: 'center', gap: 6,
                  padding: '6px 10px 6px 12px', borderRadius: 16,
                  background: 'rgba(255,255,255,0.6)', border: '1px solid rgba(196,175,168,0.35)',
                }}>
                  <span style={{ fontFamily: 'Cormorant Garamond, serif', fontSize: 14, color: '#3B3330' }}>
                    {item.quantity}{item.unit ? ` ${item.unit}` : ''} {item.name}
                  </span>
                  <button
                    onClick={() => setStaged(prev => prev.filter(s => s._sid !== item._sid))}
                    style={{ background: 'none', border: 'none', cursor: 'pointer',
                      color: 'rgba(122,106,101,0.5)', fontSize: 14, lineHeight: 1, padding: 0 }}
                  >×</button>
                </div>
              ))}
            </div>
            <button
              onClick={handleCommitManual}
              style={{
                width: '100%', padding: '11px 0', borderRadius: 22,
                background: 'rgba(59,51,48,0.85)', border: 'none',
                color: '#F2EDE8', fontFamily: 'Cinzel, serif', fontSize: 10,
                letterSpacing: '0.2em', textTransform: 'uppercase', cursor: 'pointer',
              }}
            >
              Add {staged.length} Item{staged.length !== 1 ? 's' : ''} to List
            </button>
          </div>
        )}
      </div>
    </div>
  )
}
